create schema if not exists core;

create table if not exists core.app_user (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  department text not null default '',
  role text not null default 'USER' check (role in ('ADMIN', 'USER')),
  active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists core.audit_log (
  id bigint generated by default as identity primary key,
  actor uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text not null,
  before jsonb,
  after jsonb,
  at timestamptz not null default now()
);

create index if not exists app_user_role_active_idx on core.app_user(role, active);
create index if not exists audit_log_target_idx on core.audit_log(target_type, target_id);
create index if not exists audit_log_actor_idx on core.audit_log(actor);

create or replace function core.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_user_set_updated_at on core.app_user;
create trigger app_user_set_updated_at
before update on core.app_user
for each row execute function core.set_updated_at();

create or replace function core.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  insert into core.app_user (user_id, email, name, department)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'name', ''),
    coalesce(new.raw_user_meta_data ->> 'department', '')
  )
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function core.handle_new_user();

insert into core.app_user (user_id, email, name, department)
select id, coalesce(email, ''), coalesce(raw_user_meta_data ->> 'name', ''), coalesce(raw_user_meta_data ->> 'department', '')
from auth.users
on conflict (user_id) do nothing;

create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select exists (
    select 1 from core.app_user
    where user_id = auth.uid()
      and role = 'ADMIN'
      and active = true
  );
$$;

create or replace function core.update_app_user(
  p_target_id uuid,
  p_role text,
  p_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = core, public
as $$
declare
  before_row core.app_user%rowtype;
  after_row core.app_user%rowtype;
begin
  if not core.is_admin() then
    raise exception '관리자 권한이 필요합니다.' using errcode = '42501';
  end if;
  if p_target_id = auth.uid() and (p_role <> 'ADMIN' or p_active is not true) then
    raise exception '자신의 관리자 권한과 활성 상태는 변경할 수 없습니다.' using errcode = '42501';
  end if;

  select * into before_row from core.app_user where user_id = p_target_id for update;
  if not found then
    raise exception '사용자를 찾을 수 없습니다.' using errcode = 'P0002';
  end if;

  update core.app_user
     set role = p_role, active = p_active
   where user_id = p_target_id
   returning * into after_row;

  insert into core.audit_log (actor, action, target_type, target_id, before, after)
  values (
    auth.uid(),
    case when before_row.role <> after_row.role then 'USER_ROLE_CHANGED' else 'USER_ACTIVE_CHANGED' end,
    'app_user',
    p_target_id::text,
    to_jsonb(before_row),
    to_jsonb(after_row)
  );

  return to_jsonb(after_row);
end;
$$;

create or replace function core.record_login()
returns void
language sql
security definer
set search_path = core, public
as $$
  update core.app_user
     set last_login_at = now()
   where user_id = auth.uid() and active = true;
$$;

alter table core.app_user enable row level security;
alter table core.audit_log enable row level security;
alter table core.leadtime_plan enable row level security;
alter table core.usage_profile enable row level security;

revoke all on core.app_user from anon;
revoke all on core.audit_log from anon;
revoke all on core.leadtime_plan from anon;
revoke all on core.usage_profile from anon;
revoke all on all tables in schema core from anon;

grant usage on schema core to authenticated;
grant select on core.app_user to authenticated;
grant select, update on core.app_user to authenticated;
grant insert on core.audit_log to authenticated;
grant select on core.audit_log to authenticated;
grant select on core.leadtime_plan, core.usage_profile to authenticated;
grant insert, update, delete on core.leadtime_plan, core.usage_profile to authenticated;
grant execute on function core.update_app_user(uuid, text, boolean) to authenticated;
revoke execute on function core.update_app_user(uuid, text, boolean) from anon;
grant execute on function core.record_login() to authenticated;
revoke execute on function core.record_login() from anon;

drop policy if exists app_user_self_select on core.app_user;
create policy app_user_self_select on core.app_user
for select to authenticated
using (user_id = auth.uid() or core.is_admin());

drop policy if exists app_user_admin_update on core.app_user;
create policy app_user_admin_update on core.app_user
for update to authenticated
using (core.is_admin())
with check (core.is_admin());

drop policy if exists audit_log_admin_select on core.audit_log;
create policy audit_log_admin_select on core.audit_log
for select to authenticated
using (core.is_admin());

drop policy if exists audit_log_admin_insert on core.audit_log;
create policy audit_log_admin_insert on core.audit_log
for insert to authenticated
with check (core.is_admin() and actor = auth.uid());

drop policy if exists leadtime_plan_authenticated_select on core.leadtime_plan;
create policy leadtime_plan_authenticated_select on core.leadtime_plan
for select to authenticated using (true);

drop policy if exists leadtime_plan_admin_mutation on core.leadtime_plan;
create policy leadtime_plan_admin_mutation on core.leadtime_plan
for all to authenticated
using (core.is_admin())
with check (core.is_admin());

drop policy if exists usage_profile_authenticated_select on core.usage_profile;
create policy usage_profile_authenticated_select on core.usage_profile
for select to authenticated using (true);

drop policy if exists usage_profile_admin_mutation on core.usage_profile;
create policy usage_profile_admin_mutation on core.usage_profile
for all to authenticated
using (core.is_admin())
with check (core.is_admin());
